version: '3.8'
services:
 database:
  container_name: influxdb
  image: influx_image
  restart: always
  ports: 
    - "8086:8086"
  build: 
    context: .
    dockerfile: Modulo_4/InfluxDB/Dockerfile
  networks: 
    default:
      aliases: 
        - influxdb


  broker:
    container_name: rabbit
    image: rabbit_image
    restart: always
    ports: 
      - "1883:1883"
      - "15672:15672"
      - "5672:5672"
    build: 
      context: .
      dockerfile: Modulo_4/Rabbit/Dockerfile
    networks: 
      default:
        aliases: 
          - influxdb


  visualizador:
    container_name: grafana
    image: grafana_image
    restart: always
    ports: 
      - "3000:3000"

    build: 
      context: .
      dockerfile: Modulo_4/Grafana/Dockerfile



  telegraf:
    container_name: telegraf
    image: telegraf:1.25.0
    restart: always

networks:
  default:
  ipam:
    driver: default
    config:
      -subnet:"127."